// Code generated by protoc-gen-go.
// source: github.com/myodc/geo-srv/proto/location/search/search.proto
// DO NOT EDIT!

/*
Package search is a generated protocol buffer package.

It is generated from these files:
	github.com/myodc/geo-srv/proto/location/search/search.proto

It has these top-level messages:
	Request
	Response
*/
package search

import proto "github.com/golang/protobuf/proto"
import common "github.com/myodc/geo-srv/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Request struct {
	Center      *common.Location `protobuf:"bytes,1,opt,name=center" json:"center,omitempty"`
	Radius      float64          `protobuf:"fixed64,2,opt,name=radius" json:"radius,omitempty"`
	Type        string           `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	NumEntities int64            `protobuf:"varint,4,opt,name=numEntities" json:"numEntities,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetCenter() *common.Location {
	if m != nil {
		return m.Center
	}
	return nil
}

type Response struct {
	Entities []*common.Entity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetEntities() []*common.Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
}
