// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/location-srv/proto/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Point struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4bbb12b653f31d, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Point) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Entity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Location             *Point   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e4bbb12b653f31d, []int{1}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Entity) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*Entity)(nil), "Entity")
}

func init() {
	proto.RegisterFile("github.com/microhq/location-srv/proto/common.proto", fileDescriptor_5e4bbb12b653f31d)
}

var fileDescriptor_5e4bbb12b653f31d = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0x89, 0xb6, 0xa2, 0x53, 0xe8, 0x21, 0x27, 0x29, 0x3d, 0x88, 0x27, 0x2f, 0x35, 0x60,
	0x9f, 0xa1, 0x77, 0xc9, 0x0b, 0x14, 0x8d, 0xa2, 0x03, 0x26, 0xe3, 0xea, 0xb8, 0xe0, 0xdb, 0x2f,
	0x1b, 0x59, 0xbd, 0xcd, 0xfc, 0x1f, 0x7c, 0x7c, 0x50, 0x0d, 0xc8, 0xe3, 0xd6, 0x96, 0x86, 0xac,
	0xb2, 0x68, 0x16, 0x1a, 0x6f, 0x6a, 0x22, 0xd3, 0x30, 0x92, 0xfb, 0x59, 0x97, 0xbb, 0x9a, 0x17,
	0x62, 0x52, 0x86, 0xac, 0x25, 0x57, 0xfa, 0x27, 0xff, 0x87, 0xf7, 0x9a, 0xd0, 0xb1, 0xfc, 0x82,
	0x78, 0x6a, 0x18, 0x79, 0xeb, 0xfa, 0x54, 0x64, 0xa2, 0x10, 0xfa, 0xfc, 0xe5, 0x37, 0x24, 0x13,
	0xb9, 0xe1, 0x80, 0x81, 0x87, 0xd7, 0xf0, 0xa4, 0x8c, 0xb6, 0x5f, 0xb9, 0xb1, 0x73, 0x1a, 0x66,
	0xa2, 0x08, 0xf5, 0x35, 0xe4, 0x35, 0x44, 0x7f, 0x8e, 0x91, 0x77, 0xf9, 0x09, 0x01, 0x76, 0xde,
	0x9d, 0xe8, 0x00, 0x3b, 0x29, 0xe1, 0x8d, 0xf7, 0xf9, 0x10, 0x26, 0xda, 0xdf, 0x32, 0x87, 0xf8,
	0x55, 0xec, 0x55, 0x1f, 0x55, 0x54, 0xfa, 0x3e, 0x7d, 0xee, 0x6d, 0xe4, 0xcb, 0x7f, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x23, 0x0c, 0x3e, 0x9b, 0xef, 0x00, 0x00, 0x00,
}
