// Code generated by protoc-gen-go.
// source: github.com/micro/geo-srv/proto/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/geo-srv/proto/common.proto

It has these top-level messages:
	Location
	Entity
*/
package common

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Location struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Timestamp int64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}

type Entity struct {
	Id       string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type     string    `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Location *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}

func (m *Entity) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
}
