// Code generated by protoc-gen-go.
// source: github.com/micro/geo-srv/proto/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/geo-srv/proto/common.proto

It has these top-level messages:
	Point
	Entity
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Timestamp int64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Point) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Entity struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Location *Point `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Entity) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*Entity)(nil), "Entity")
}

func init() { proto.RegisterFile("github.com/micro/geo-srv/proto/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0x8a, 0x83, 0x30,
	0x10, 0x86, 0x89, 0xee, 0x8a, 0xce, 0xc2, 0x1e, 0x72, 0x92, 0xd2, 0x83, 0x78, 0x12, 0x4a, 0x0d,
	0xb4, 0xcf, 0xd0, 0xbb, 0xe4, 0x05, 0x8a, 0x46, 0xb1, 0x03, 0x26, 0x23, 0x3a, 0x16, 0x7c, 0xfb,
	0xd2, 0x08, 0x7a, 0x9b, 0xf9, 0x3e, 0xf8, 0xf8, 0xe1, 0xd2, 0x23, 0xbf, 0x96, 0xa6, 0x34, 0x64,
	0x95, 0x45, 0x33, 0x91, 0xea, 0x3b, 0xba, 0xce, 0xd3, 0x5b, 0x8d, 0x13, 0x31, 0x29, 0x43, 0xd6,
	0x92, 0x2b, 0xfd, 0x93, 0x3f, 0xe1, 0xb7, 0x22, 0x74, 0x2c, 0x4f, 0x10, 0x0f, 0x35, 0x23, 0x2f,
	0x6d, 0x97, 0x8a, 0x4c, 0x14, 0x42, 0xef, 0xbf, 0x3c, 0x43, 0x32, 0x90, 0xeb, 0x37, 0x19, 0x78,
	0x79, 0x80, 0xaf, 0x65, 0xb4, 0xdd, 0xcc, 0xb5, 0x1d, 0xd3, 0x30, 0x13, 0x45, 0xa8, 0x0f, 0x90,
	0x57, 0x10, 0x3d, 0x1c, 0x23, 0xaf, 0xf2, 0x1f, 0x02, 0x6c, 0x7d, 0x3b, 0xd1, 0x01, 0xb6, 0x52,
	0xc2, 0x0f, 0xaf, 0xe3, 0x16, 0x4c, 0xb4, 0xbf, 0x65, 0x0e, 0xf1, 0x40, 0xa6, 0x66, 0x24, 0xe7,
	0x53, 0x7f, 0xb7, 0xa8, 0xf4, 0xfb, 0xf4, 0xce, 0x9b, 0xc8, 0x2f, 0xbf, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0x59, 0x81, 0xd9, 0xe8, 0x00, 0x00, 0x00,
}
