// Code generated by protoc-gen-go.
// source: github.com/myodc/geo-srv/proto/location/read/read.proto
// DO NOT EDIT!

/*
Package read is a generated protocol buffer package.

It is generated from these files:
	github.com/myodc/geo-srv/proto/location/read/read.proto

It has these top-level messages:
	Request
	Response
*/
package read

import proto "github.com/golang/protobuf/proto"
import common "github.com/myodc/geo-srv/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Request struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Entity *common.Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
}
