// Code generated by protoc-gen-go.
// source: github.com/micro/geo-srv/proto/location/location.proto
// DO NOT EDIT!

/*
Package location is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/geo-srv/proto/location/location.proto

It has these top-level messages:
	ReadRequest
	ReadResponse
	SaveRequest
	SaveResponse
	SearchRequest
	SearchResponse
*/
package location

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/micro/geo-srv/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Entity *common.Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadResponse) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveRequest struct {
	Entity *common.Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *SaveRequest) Reset()                    { *m = SaveRequest{} }
func (m *SaveRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()               {}
func (*SaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SaveRequest) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveResponse struct {
}

func (m *SaveResponse) Reset()                    { *m = SaveResponse{} }
func (m *SaveResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()               {}
func (*SaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SearchRequest struct {
	Center      *common.Point `protobuf:"bytes,1,opt,name=center" json:"center,omitempty"`
	Radius      float64       `protobuf:"fixed64,2,opt,name=radius" json:"radius,omitempty"`
	Type        string        `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	NumEntities int64         `protobuf:"varint,4,opt,name=numEntities" json:"numEntities,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchRequest) GetCenter() *common.Point {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *SearchRequest) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *SearchRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchRequest) GetNumEntities() int64 {
	if m != nil {
		return m.NumEntities
	}
	return 0
}

type SearchResponse struct {
	Entities []*common.Entity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchResponse) GetEntities() []*common.Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*SaveRequest)(nil), "SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "SaveResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg))
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}) error {
	return s.Subscribe(s.NewSubscriber(topic, h))
}

// Client API for Location service

type LocationClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type locationClient struct {
	c           client.Client
	serviceName string
}

func NewLocationClient(serviceName string, c client.Client) LocationClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "location"
	}
	return &locationClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *locationClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Location service

type LocationHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Save(context.Context, *SaveRequest, *SaveResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterLocationHandler(s server.Server, hdlr LocationHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Location{hdlr}, opts...))
}

type Location struct {
	LocationHandler
}

func (h *Location) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.LocationHandler.Read(ctx, in, out)
}

func (h *Location) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.LocationHandler.Save(ctx, in, out)
}

func (h *Location) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.LocationHandler.Search(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/micro/geo-srv/proto/location/location.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x6a, 0xf3, 0x30,
	0x10, 0x8c, 0x92, 0xe0, 0x2f, 0xdf, 0xda, 0x71, 0x41, 0x87, 0x62, 0x0c, 0x6d, 0x8d, 0x4a, 0x21,
	0x10, 0x2a, 0x43, 0x4a, 0xfb, 0x06, 0xbd, 0xf5, 0x50, 0x94, 0x27, 0x70, 0xec, 0x25, 0x11, 0xd4,
	0x56, 0x2a, 0xc9, 0x81, 0x1c, 0x7a, 0xec, 0x7b, 0x97, 0xc8, 0x72, 0x70, 0x4e, 0xb9, 0xed, 0xce,
	0xce, 0xfe, 0xcc, 0x2c, 0xbc, 0x6d, 0xa5, 0xdd, 0xb5, 0x1b, 0x5e, 0xaa, 0x3a, 0xaf, 0x65, 0xa9,
	0x55, 0xbe, 0x45, 0xf5, 0x6c, 0xf4, 0x21, 0xdf, 0x6b, 0x65, 0x55, 0xfe, 0xa5, 0xca, 0xc2, 0x4a,
	0xd5, 0x9c, 0x03, 0xee, 0xf0, 0x74, 0x79, 0xa5, 0xaf, 0x54, 0x75, 0xdd, 0x93, 0xd9, 0x1d, 0x84,
	0x02, 0x8b, 0x4a, 0xe0, 0x77, 0x8b, 0xc6, 0xd2, 0x18, 0xc6, 0xb2, 0x4a, 0x48, 0x46, 0x16, 0xff,
	0xc5, 0x58, 0x56, 0x2c, 0x87, 0xa8, 0x2b, 0x9b, 0xbd, 0x6a, 0x0c, 0xd2, 0x07, 0x08, 0xb0, 0xb1,
	0xd2, 0x1e, 0x1d, 0x27, 0x5c, 0xfd, 0xe3, 0xef, 0x2e, 0x15, 0x1e, 0x66, 0x1c, 0xc2, 0x75, 0x71,
	0xc0, 0x7e, 0xde, 0x55, 0x7e, 0x0c, 0x51, 0xc7, 0xef, 0x16, 0xb0, 0x1f, 0x98, 0xaf, 0xb1, 0xd0,
	0xe5, 0xae, 0x9f, 0x70, 0x0f, 0x41, 0x89, 0x8d, 0x45, 0xed, 0x27, 0x04, 0xfc, 0x53, 0xc9, 0xc6,
	0x0a, 0x8f, 0xd2, 0x5b, 0x08, 0x74, 0x51, 0xc9, 0xd6, 0x24, 0xe3, 0x8c, 0x2c, 0x88, 0xf0, 0x19,
	0xa5, 0x30, 0xb5, 0xc7, 0x3d, 0x26, 0x13, 0xa7, 0xc5, 0xc5, 0x34, 0x83, 0xb0, 0x69, 0x6b, 0x77,
	0x81, 0x44, 0x93, 0x4c, 0x33, 0xb2, 0x98, 0x88, 0x21, 0xc4, 0x5e, 0x21, 0xee, 0xd7, 0x7b, 0xc5,
	0x8f, 0x30, 0xc3, 0xbe, 0x81, 0x64, 0x93, 0xa1, 0x86, 0x73, 0x61, 0xf5, 0x4b, 0x60, 0xf6, 0xe1,
	0xbf, 0x40, 0x9f, 0x60, 0x7a, 0xf2, 0x8c, 0x46, 0x7c, 0xe0, 0x6c, 0x3a, 0xe7, 0x43, 0x23, 0xd9,
	0xe8, 0x44, 0x3b, 0x29, 0xa7, 0x11, 0x1f, 0x18, 0x96, 0xce, 0xf9, 0x85, 0x1d, 0x23, 0xba, 0x84,
	0xa0, 0xbb, 0x88, 0xc6, 0xfc, 0xc2, 0x99, 0xf4, 0x86, 0x5f, 0x9e, 0xca, 0x46, 0x9b, 0xc0, 0x3d,
	0xf5, 0xe5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x65, 0x9d, 0xb8, 0xfa, 0x3b, 0x02, 0x00, 0x00,
}
