// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/location-srv/proto/location/location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/microhq/location-srv/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{0}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Entity               *proto1.Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{1}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetEntity() *proto1.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveRequest struct {
	Entity               *proto1.Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{2}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetEntity() *proto1.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{3}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

type SearchRequest struct {
	Center               *proto1.Point `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Radius               float64       `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
	Type                 string        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	NumEntities          int64         `protobuf:"varint,4,opt,name=numEntities,proto3" json:"numEntities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{4}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetCenter() *proto1.Point {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *SearchRequest) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *SearchRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchRequest) GetNumEntities() int64 {
	if m != nil {
		return m.NumEntities
	}
	return 0
}

type SearchResponse struct {
	Entities             []*proto1.Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3314c2d7d902bf, []int{5}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetEntities() []*proto1.Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*SaveRequest)(nil), "SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "SaveResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/location-srv/proto/location/location.proto", fileDescriptor_dc3314c2d7d902bf)
}

var fileDescriptor_dc3314c2d7d902bf = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x97, 0x6d, 0xd4, 0xf9, 0xb6, 0xab, 0x90, 0x83, 0x94, 0x82, 0x5a, 0x22, 0xc2, 0x40,
	0x4c, 0x61, 0xe2, 0xd1, 0xa3, 0x37, 0x0f, 0x92, 0x7d, 0x82, 0xae, 0x7d, 0x71, 0x01, 0xdb, 0x6c,
	0x49, 0x3a, 0xd8, 0xc1, 0xa3, 0xdf, 0x5b, 0x96, 0xa6, 0xa3, 0x3b, 0xe9, 0x2d, 0x79, 0xf2, 0xbc,
	0x7f, 0x9e, 0x5f, 0xe0, 0xf5, 0x53, 0xda, 0x4d, 0xbb, 0xe6, 0xa5, 0xaa, 0xf3, 0x5a, 0x96, 0x5a,
	0x6d, 0x76, 0xf9, 0x97, 0x2a, 0x0b, 0x2b, 0x55, 0xf3, 0x64, 0xf4, 0x3e, 0xdf, 0x6a, 0x65, 0xd5,
	0x49, 0x3a, 0x1d, 0xb8, 0xd3, 0xd3, 0xe5, 0xff, 0xca, 0x4b, 0x55, 0xd7, 0x7d, 0x0d, 0xbb, 0x81,
	0x50, 0x60, 0x51, 0x09, 0xdc, 0xb5, 0x68, 0x2c, 0x8d, 0x61, 0x2c, 0xab, 0x84, 0x64, 0x64, 0x71,
	0x29, 0xc6, 0xb2, 0x62, 0x39, 0x44, 0xdd, 0xb3, 0xd9, 0xaa, 0xc6, 0x20, 0xbd, 0x83, 0x00, 0x1b,
	0x2b, 0xed, 0xc1, 0x79, 0xc2, 0xe5, 0x05, 0x7f, 0x73, 0x57, 0xe1, 0x65, 0xc6, 0x21, 0x5c, 0x15,
	0x7b, 0xec, 0xfb, 0xfd, 0xe9, 0x8f, 0x21, 0xea, 0xfc, 0xdd, 0x00, 0xf6, 0x0d, 0xf3, 0x15, 0x16,
	0xba, 0xdc, 0xf4, 0x1d, 0x6e, 0x21, 0x28, 0xb1, 0xb1, 0xa8, 0x7d, 0x87, 0x80, 0x7f, 0x28, 0xd9,
	0x58, 0xe1, 0x55, 0x7a, 0x0d, 0x81, 0x2e, 0x2a, 0xd9, 0x9a, 0x64, 0x9c, 0x91, 0x05, 0x11, 0xfe,
	0x46, 0x29, 0x4c, 0xed, 0x61, 0x8b, 0xc9, 0xc4, 0x65, 0x71, 0x67, 0x9a, 0x41, 0xd8, 0xb4, 0xb5,
	0xdb, 0x40, 0xa2, 0x49, 0xa6, 0x19, 0x59, 0x4c, 0xc4, 0x50, 0x62, 0x2f, 0x10, 0xf7, 0xe3, 0x7d,
	0xe2, 0x7b, 0x98, 0x61, 0x5f, 0x40, 0xb2, 0xc9, 0x30, 0xc3, 0xe9, 0x61, 0xf9, 0x43, 0x60, 0xf6,
	0xee, 0x49, 0xd3, 0x07, 0x98, 0x1e, 0x99, 0xd1, 0x88, 0x0f, 0xc8, 0xa6, 0x73, 0x3e, 0x04, 0xc9,
	0x46, 0x47, 0xdb, 0x31, 0x39, 0x8d, 0xf8, 0x00, 0x58, 0x3a, 0xe7, 0x67, 0x38, 0x46, 0xf4, 0x11,
	0x82, 0x6e, 0x23, 0x1a, 0xf3, 0x33, 0x32, 0xe9, 0x15, 0x3f, 0x5f, 0x95, 0x8d, 0xd6, 0x81, 0xfb,
	0xd4, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xa6, 0x53, 0x1b, 0x49, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationClient is the client API for Location service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type locationClient struct {
	cc *grpc.ClientConn
}

func NewLocationClient(cc *grpc.ClientConn) LocationClient {
	return &locationClient{cc}
}

func (c *locationClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/Location/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/Location/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/Location/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServer is the server API for Location service.
type LocationServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterLocationServer(s *grpc.Server, srv LocationServer) {
	s.RegisterService(&_Location_serviceDesc, srv)
}

func _Location_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Location/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Location/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Location/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Location_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Location",
	HandlerType: (*LocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Location_Read_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Location_Save_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Location_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/microhq/location-srv/proto/location/location.proto",
}
