// Code generated by protoc-gen-go.
// source: github.com/micro/geo-srv/proto/location/location.proto
// DO NOT EDIT!

/*
Package location is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/geo-srv/proto/location/location.proto

It has these top-level messages:
	ReadRequest
	ReadResponse
	SaveRequest
	SaveResponse
	SearchRequest
	SearchResponse
*/
package location

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/micro/geo-srv/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReadResponse struct {
	Entity *common.Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadResponse) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveRequest struct {
	Entity *common.Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *SaveRequest) Reset()                    { *m = SaveRequest{} }
func (m *SaveRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()               {}
func (*SaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SaveRequest) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SaveResponse struct {
}

func (m *SaveResponse) Reset()                    { *m = SaveResponse{} }
func (m *SaveResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()               {}
func (*SaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SearchRequest struct {
	Center      *common.Point `protobuf:"bytes,1,opt,name=center" json:"center,omitempty"`
	Radius      float64       `protobuf:"fixed64,2,opt,name=radius" json:"radius,omitempty"`
	Type        string        `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	NumEntities int64         `protobuf:"varint,4,opt,name=numEntities" json:"numEntities,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchRequest) GetCenter() *common.Point {
	if m != nil {
		return m.Center
	}
	return nil
}

type SearchResponse struct {
	Entities []*common.Entity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchResponse) GetEntities() []*common.Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*SaveRequest)(nil), "SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "SaveResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Location service

type LocationClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type locationClient struct {
	c           client.Client
	serviceName string
}

func NewLocationClient(serviceName string, c client.Client) LocationClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "location"
	}
	return &locationClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *locationClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Location.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Location service

type LocationHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Save(context.Context, *SaveRequest, *SaveResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterLocationHandler(s server.Server, hdlr LocationHandler) {
	s.Handle(s.NewHandler(&Location{hdlr}))
}

type Location struct {
	LocationHandler
}

func (h *Location) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.LocationHandler.Read(ctx, in, out)
}

func (h *Location) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.LocationHandler.Save(ctx, in, out)
}

func (h *Location) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.LocationHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x6a, 0x83, 0x40,
	0x14, 0x85, 0x63, 0x12, 0xa6, 0xe9, 0xd5, 0x58, 0x98, 0x42, 0x6b, 0x5c, 0x85, 0x81, 0xfe, 0x80,
	0x74, 0x84, 0x14, 0xfa, 0x06, 0xdd, 0x75, 0x51, 0x92, 0x5d, 0x77, 0x46, 0x2f, 0xc9, 0x40, 0x75,
	0xec, 0xcc, 0x18, 0xc8, 0x03, 0xf4, 0xbd, 0x3b, 0xfe, 0x15, 0x5d, 0x94, 0xee, 0xf4, 0xdc, 0xef,
	0x5c, 0xcf, 0xb9, 0xc2, 0xcb, 0x41, 0x98, 0x63, 0xb5, 0xe7, 0xa9, 0xcc, 0xe3, 0x5c, 0xa4, 0x4a,
	0xc6, 0x07, 0x94, 0x4f, 0x5a, 0x9d, 0xe2, 0x52, 0x49, 0x23, 0xe3, 0x4f, 0x99, 0x26, 0x46, 0xc8,
	0xe2, 0xf7, 0x81, 0x37, 0x7a, 0x18, 0xfd, 0xe3, 0xb3, 0x7a, 0xde, 0xc3, 0x6c, 0x05, 0xee, 0x16,
	0x93, 0x6c, 0x8b, 0x5f, 0x15, 0x6a, 0x43, 0x01, 0xa6, 0x22, 0x0b, 0x9c, 0xb5, 0xf3, 0x78, 0xc9,
	0x1e, 0xc0, 0x6b, 0x47, 0xba, 0x94, 0x85, 0x46, 0x7a, 0x0b, 0x04, 0x0b, 0x23, 0xcc, 0xb9, 0x99,
	0xbb, 0x9b, 0x0b, 0xfe, 0xda, 0xbc, 0xb2, 0x7b, 0x70, 0x77, 0xc9, 0x09, 0xfb, 0x1d, 0x7f, 0x72,
	0x3e, 0x78, 0x2d, 0xd7, 0x2e, 0x64, 0x1f, 0xb0, 0xdc, 0x61, 0xa2, 0xd2, 0x63, 0xef, 0xbc, 0x01,
	0x92, 0x5a, 0x2b, 0xaa, 0xce, 0x49, 0xf8, 0xbb, 0x14, 0x85, 0xa1, 0x3e, 0x10, 0x95, 0x64, 0xa2,
	0xd2, 0xc1, 0xd4, 0xea, 0x0e, 0xf5, 0x60, 0x6e, 0xce, 0x25, 0x06, 0xb3, 0x3a, 0x27, 0xbd, 0x06,
	0xb7, 0xa8, 0xf2, 0xe6, 0x1b, 0x02, 0x75, 0x30, 0xb7, 0xe2, 0x8c, 0x45, 0xe0, 0xf7, 0xbb, 0xbb,
	0xf8, 0x2b, 0x58, 0x60, 0xcf, 0x38, 0xeb, 0xd9, 0x20, 0xd8, 0xe6, 0xdb, 0x81, 0xc5, 0x5b, 0x77,
	0x44, 0x7a, 0x07, 0xf3, 0xba, 0x36, 0xf5, 0xf8, 0xe0, 0x30, 0xe1, 0x92, 0x0f, 0x6f, 0xc1, 0x26,
	0x35, 0x56, 0x97, 0xb1, 0xd8, 0xa0, 0xbb, 0xc5, 0x46, 0x0d, 0x27, 0x34, 0x02, 0xd2, 0xe6, 0xa0,
	0x3e, 0x1f, 0x95, 0x0d, 0xaf, 0xf8, 0x38, 0x20, 0x9b, 0xec, 0x49, 0xf3, 0x4f, 0x9e, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x81, 0xd8, 0x4c, 0x1f, 0xfa, 0x01, 0x00, 0x00,
}
